services:
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    container_name: frontend-container
    depends_on:
      - api
    develop:
      watch:
        - action: sync
          path: ./
          target: .
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
  api:
    build: ./API
    env_file:
      - .env
    ports:
      - '3000:3000'
    container_name: API-container
    develop:
      watch:
        - action: sync
          path: ./
          target: .
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json